/** CAPEX Tracker — capital expenditure management and depreciation */

export type DepreciationMethod = 'straight-line' | 'declining-balance'
export type AssetStatus = 'Active' | 'Fully Depreciated' | 'Disposed'

export interface CAPEXProject {
  id: string
  name: string
  totalCost: number          // KES acquisition cost
  dateAcquired: string       // ISO date string (YYYY-MM)
  usefulLifeYears: number    // expected useful life
  salvageValue: number       // residual value at end of life
  method: DepreciationMethod
  annualRevenueImpact?: number  // optional: revenue generated by this asset
}

export interface CAPEXResult {
  id: string
  name: string
  totalCost: number
  annualDepreciation: number
  accumulatedDepreciation: number
  currentBookValue: number
  ageMonths: number
  ageYears: number
  remainingLifeYears: number
  status: AssetStatus
  roi: number | null          // % — only if annualRevenueImpact provided
  paybackYears: number | null // years — only if annualRevenueImpact provided
  netBookValuePct: number     // currentBookValue / totalCost * 100
}

export interface CAPEXSummary {
  projects: CAPEXResult[]
  totalInvested: number
  totalBookValue: number
  totalAnnualDepreciation: number
  totalAccumulatedDepreciation: number
  weightedRemainingLife: number   // years
  assetsByStatus: Record<AssetStatus, number>
}

function getAgeMonths(dateAcquired: string): number {
  const acquired = new Date(dateAcquired + '-01')
  const now = new Date()
  return Math.max(0,
    (now.getFullYear() - acquired.getFullYear()) * 12 +
    (now.getMonth() - acquired.getMonth())
  )
}

function calcDepreciation(project: CAPEXProject, ageYears: number): {
  annual: number
  accumulated: number
  bookValue: number
} {
  const depreciableAmount = project.totalCost - project.salvageValue

  if (project.method === 'straight-line') {
    const annual = project.usefulLifeYears > 0
      ? depreciableAmount / project.usefulLifeYears
      : 0
    const accumulated = Math.min(depreciableAmount, annual * ageYears)
    const bookValue = Math.max(project.salvageValue, project.totalCost - accumulated)
    return { annual, accumulated, bookValue }
  }

  // Declining balance (double-declining = 2 / useful life)
  const rate = project.usefulLifeYears > 0 ? (2 / project.usefulLifeYears) : 0
  let bookValue = project.totalCost
  let accumulated = 0
  const fullYears = Math.floor(ageYears)
  for (let y = 0; y < fullYears; y++) {
    const dep = Math.max(0, bookValue * rate)
    const depToSalvage = Math.max(0, bookValue - project.salvageValue)
    const actualDep = Math.min(dep, depToSalvage)
    bookValue -= actualDep
    accumulated += actualDep
    if (bookValue <= project.salvageValue) break
  }
  // Annual = first year depreciation for display
  const firstYearDep = project.totalCost * rate
  return { annual: firstYearDep, accumulated, bookValue: Math.max(project.salvageValue, bookValue) }
}

export function calculateCAPEX(projects: CAPEXProject[]): CAPEXSummary {
  const results: CAPEXResult[] = projects.map(project => {
    const ageMonths = getAgeMonths(project.dateAcquired)
    const ageYears  = ageMonths / 12
    const { annual, accumulated, bookValue } = calcDepreciation(project, ageYears)
    const remainingLifeYears = Math.max(0, project.usefulLifeYears - ageYears)

    let status: AssetStatus = 'Active'
    if (bookValue <= project.salvageValue) status = 'Fully Depreciated'

    const roi = project.annualRevenueImpact != null && project.totalCost > 0
      ? ((project.annualRevenueImpact - annual) / project.totalCost) * 100
      : null

    const paybackYears = project.annualRevenueImpact != null && project.annualRevenueImpact > 0
      ? project.totalCost / project.annualRevenueImpact
      : null

    return {
      id: project.id,
      name: project.name,
      totalCost: project.totalCost,
      annualDepreciation: annual,
      accumulatedDepreciation: accumulated,
      currentBookValue: bookValue,
      ageMonths,
      ageYears,
      remainingLifeYears,
      status,
      roi,
      paybackYears,
      netBookValuePct: project.totalCost > 0 ? (bookValue / project.totalCost) * 100 : 0,
    }
  })

  const totalInvested = results.reduce((s, r) => s + r.totalCost, 0)
  const totalBookValue = results.reduce((s, r) => s + r.currentBookValue, 0)
  const totalAnnualDepreciation = results.reduce((s, r) => s + r.annualDepreciation, 0)
  const totalAccumulatedDepreciation = results.reduce((s, r) => s + r.accumulatedDepreciation, 0)
  const weightedRemainingLife = totalInvested > 0
    ? results.reduce((s, r) => s + r.remainingLifeYears * r.totalCost, 0) / totalInvested
    : 0

  const assetsByStatus: Record<AssetStatus, number> = {
    Active: 0, 'Fully Depreciated': 0, Disposed: 0,
  }
  for (const r of results) assetsByStatus[r.status]++

  return {
    projects: results,
    totalInvested,
    totalBookValue,
    totalAnnualDepreciation,
    totalAccumulatedDepreciation,
    weightedRemainingLife,
    assetsByStatus,
  }
}

export const DEFAULT_PROJECTS: CAPEXProject[] = [
  { id: '1', name: 'Delivery Vehicle', totalCost: 2_000_000, dateAcquired: '2023-01', usefulLifeYears: 5, salvageValue: 200_000, method: 'straight-line', annualRevenueImpact: 600_000 },
  { id: '2', name: 'Office Equipment', totalCost: 300_000, dateAcquired: '2022-06', usefulLifeYears: 3, salvageValue: 0, method: 'straight-line' },
  { id: '3', name: 'Production Machinery', totalCost: 5_000_000, dateAcquired: '2023-07', usefulLifeYears: 10, salvageValue: 500_000, method: 'declining-balance', annualRevenueImpact: 1_500_000 },
]
